### ISSUE TITLE
VagrantFile Notes

### ISSUE THREAD

**Issue by tomjn** [svandragt/cuttlefish#119]
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
```
You should add `Vagrant.require_version '>= 2.2.4'` or something similar

```ruby
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
```

host manager might be better than hostsupdater but it has issues and isn't super active maintenance wise, especially on Windows. Instead consider `vagrant-goodhost` which relies on the golang goodhost project to avoid falling into disrepair.

You can also declare it as a local plugin so it doesn't have to be installed system wide.

```ruby
  # Enable writing to the logs and cache folder through permissions
  config.vm.synced_folder ".", "/srv/app"
  config.vm.synced_folder "src/", "/srv/app/src", owner: "www-data", group: "www-data"
  config.vm.synced_folder "data/", "/srv/app/data", owner: "www-data", group: "www-data"
```

Here we have 2 overlapping mounts, virtualbox does not like this, overlapping mounts can cause performance issues and instability. It would be better to mount `/srv/app` under `www-data`

I'd also recommend disabling the `/vagrant` mount that's added by default.

For the provisioners, `File.join( '.vagrant', 'bootstrap.sh')` would be more portable than `'./.vagrant/bootstrap.sh'`

**Comment by tomjn** [comment]
`boostrap.sh` notes:

 - `$FILE` is vulnerable to parameter expansion bugs, you should use `"${FILE}"` instead. The most immediate issue it fixes is folders with spaces in them, but there are security concerns as the contents of `$FILE` are substituted as is, unquoted
 - `php7.4-common` would give you the CLI commands to turn xdebug on and off
 - You'll need to update the `xdebug.ini` to enable the modes you want to use
 - if an `apt` command faills you will never know why because of the `-qq`
 - `sudo apt-get install -y nodejs` doesn't need `sudo`
 - Ubuntu has a `nodejs` package that isn't from nodesource, it's a good idea to pin the nodesource repo. Apt uses the first available source so if Nodesource isn't available it'll use the Canonical source and you'll be missing `npm`
 - There's a more reliable version of the `apt` install command here https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/provision/provision-helpers.sh#L419

**Comment by tomjn** [comment]
`start.sh` notes:

 - it should log what it's doing so you know if it fails at which step it failed
 - the first 3 lines don't need `sudo`, files and folders in VirtualBox mounts always have the same permissions, no matter what `chmod` etc you give them they'll have what you specified in the vagrantfile
 - `sudo cp /srv/app/.vagrant/etc/ / -r` is brave!

**Comment by svandragt** [comment]
Thanks for the feedback @tomjn 🙌

**Comment by svandragt** [comment]
Cheers again, had a look into things.

> You should add `Vagrant.require_version '>= 2.2.4'` or something similar

https://github.com/hashicorp/vagrant/blob/master/CHANGELOG.md any reason for this, what feature lifts the requirement here?

> Here we have 2 overlapping mounts, virtualbox does not like this, overlapping mounts can cause performance issues and instability. It would be better to mount /srv/app under www-data

This was the old situation. That setup prevents the vagrant user from running composer and npm and editing any source files on the app because of file permissions, so it's not any good.

I'll work towards moving the data mount outside the project root, that fixes the overlap and I can read some environment variable that takes priority over the configuration values perhaps, to avoid having to configure it.

**Comment by tomjn** [comment]
> https://github.com/hashicorp/vagrant/blob/master/CHANGELOG.md any reason for this, what feature lifts the requirement here?

It's not so much that a feature is being used that you want, but rather an already fixed bug that you don't

> I'll work towards moving the data mount outside the project root, that fixes the overlap and I can read some environment variable that takes priority over the configuration values perhaps, to avoid having to configure it.

Makes sense, unmounting `/vagrant` is lowhanging fruit though and a one liner that shouldn't impact what you've done other than to speed up `vagrant up` and improve filesystem performance for the mounts you do use

**Comment by svandragt** [comment]
Removed vagrant support.
